name: hisp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics-dolfinx=0.9.0
  - festim=2.0a8
  - matplotlib
  - scipy
  - pandas
  - pint # need to install pint with conda to avoid conflicts (HTM)
  - nbconvert
  - ipykernel
  - pip
